dist: trusty
sudo: false

language: python
python:
  - "2.7"

notifications:
  email: false

# Cache PlatformIO packages using Travis CI container-based infrastructure
sudo: false
cache:
  pip: true
  directories:
  - "~/.platformio"

env:
  - TEST_PLATFORM="-e megaatmega2560"

before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - export PATH=${TRAVIS_BUILD_DIR}/buildroot/bin/:${PATH}

install:
  - pip install -U platformio

before_script:
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Generate custom version include
  - generate_version_header_for_marlin ${TRAVIS_BUILD_DIR}/Marlin/src/inc
  - cat ${TRAVIS_BUILD_DIR}/Marlin/src/inc/_Version.h
  #
script:
  #
  # Backup pins_RAMPS.h
  #
  - cp Marlin/src/pins/pins_RAMPS.h Marlin/src/pins/pins_RAMPS.h.backup
  #
  # Build with the default configurations
  #
  - restore_configs
  - build_marlin_pio ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}
